### ISSUE TITLE
Add a static method `isValid`

### ISSUE THREAD

**Issue by nijynot** [multiformats/js-multiaddr#101]
I think a static method that checks whether a string or JavaScript Object `nodeAddress` is a valid Multiaddr or not would be nice to have.

Example:
```js
const validAddr = '/ip4/0.0.0.0/tcp/0';
const notValidAddr1 = '/ip4/0.0.0.0/tcp';
const notValidAddr2 = '/ip4/0.0.0.0/ipfs/asdf';
const notValidAddr3 = { family: 123 };

console.log(Multiaddr.isValid(validAddr))
// => true

console.log(Multiaddr.isValid(notValidAddr1))
// => false

console.log(Multiaddr.isValid(notValidAddr2))
// => false

console.log(Multiaddr.isValid(notValidAddr3))
// => false
```

Would love to know what you guys think - can try to add this if it's of interest.

**Comment by jacobheun** [comment]
https://github.com/multiformats/js-mafmt is a validation library for multiaddr strings, it just requires you to know the type of address you want to check.

**Comment by nijynot** [comment]
Ah, nice, already exists! Closing.
