### ISSUE TITLE
Adding types to DefinitelyTyped

### ISSUE THREAD

**Issue by carsonfarmer** [multiformats/js-multiaddr#104]
Work ongoing here for those who might be interested in following: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41413
Note that if @jacobheun or any other maintainer is ok with having the types here, I'd be happy to PR directly to this repo instead.

**Comment by jacobheun** [comment]
@carsonfarmer I am up for including the types here. 

I'm also interested in including them in the js-libp2p repos (once the async refactor is complete).

**Comment by carsonfarmer** [comment]
Oops... Looks like it already go published as `@types/multiaddr` (it doesn't usually go that quick). But no biggie, its easy enough to pull back over here! Lemme know if you'd prefer it to be maintained here or there. I'm happy with either :)

**Comment by carsonfarmer** [comment]
I'll close this issue for now, and we can reopen the discussion if we want to pull the types here at some future date.
