### ISSUE TITLE
Export types

### ISSUE THREAD

**Issue by robertkiel** [multiformats/js-multiaddr#107]
https://github.com/multiformats/js-multiaddr/blob/9ffafdb8e52cd0c922b71333f1cb7091f4cbc58b/package.json#L6

Add the following to export types properly

```json
"types": "src/index.d.ts"
```

**Comment by jacobheun** [comment]
Good catch, would you mind submitting a PR for this?

**Comment by robertkiel** [comment]
I find a PR a bit toooo much overhead for this little change
