### ISSUE TITLE
DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

### ISSUE THREAD

**Issue by nijynot** [multiformats/js-multiaddr#108]
Getting this error when logging a Multiaddr
```
(node:20190) [DEP0079] DeprecationWarning: Custom inspection function on Objects
via .inspect() is deprecated
```

Related to [this deprecation notice](https://nodejs.org/api/deprecations.html#deprecations_dep0079_custom_inspection_function_on_objects_via_inspect).

**Comment by jacobheun** [comment]
Looks like we'll need to convert to using symbols, https://nodejs.org/api/util.html#util_util_inspect_custom. We don't support older versions of Node, so we shouldn't need to worry about handling backwards compatibility. 

Unless you need it, I'd recommend just casting the `multiaddr` to a string when logging.
```js
const addr = multiaddr('/ip4/0.0.0.0/tcp/0')
console.log(String(addr))
console.log('multiaddr: %s', addr)
```
