### ISSUE TITLE
Some security findings

### ISSUE THREAD

**Issue by aileenscott-uleska** [multiformats/js-multiaddr#127]
Hi folks,

I hope you don’t mind, we were testing out our security automation tool and ran it against your project.  A few issues came out that you may want to check out - we weren’t sure how to submit a PDF here, so we uploaded it to https://source-security.co.uk/e3291bcc-debb-4353-862d-e9c5eeb0e9ea/ if you wanna check it out.

Any issues or feedback, just let us know.

Aileen

**Comment by rvagg** [comment]
reporting as spam
