### ISSUE TITLE
Compile problem when using latest multiaddr in a browser app

### ISSUE THREAD

**Issue by mgoelzer** [multiformats/js-multiaddr#156]
The problem is described here:  https://github.com/filecoin-shipyard/browser-retrieval/issues/140

It only started recently when we upgraded to the latest libp2p in our package.json.

This issue isn't a blocker for our project, but I thought I should let the js-multiaddr project know about it.

**Comment by vasco-santos** [comment]
The `require('dns')` was added recently yes. We basically try to use the native `dns` and if it is not available, we fallback to a `dns-over-http-resolver` in https://github.com/multiformats/js-multiaddr/blob/master/src/resolvers/dns.js

While this warning does not seem to cause any issues, it is annoying. So, we should look into another way of doing this validation.
