### ISSUE TITLE
No documentation for getPeerId()

### ISSUE THREAD

**Issue by a1300** [multiformats/js-multiaddr#161]

**Comment by a1300** [comment]
Sorry, I didn't saw the API section.
@jacobheun should the `## Usage` section include the whole API? I find it confusing that the `## Usage` section only shows a subset of the API

**Comment by vasco-santos** [comment]
@a1300 with the work in https://github.com/multiformats/js-multiaddr/pull/159 we will be able to automatically generate documentation via jsdocs. This should be solved in that PR

**Comment by a1300** [comment]
@vasco-santos Thanks
