### ISSUE TITLE
Outdated README.md

### ISSUE THREAD

**Issue by vogdb** [multiformats/js-multiaddr#225]
Hi! Currently I'm looking at README.md and have some notes:
- the npm project name is `@multiformats/multiaddr` but in README `multiaddr` is used.
  An example: `npm i multiaddr` in "Install" section
- Since `v10.1.0` the package can only be loaded via `import`. `require('@multiformats/multiaddr')` will throw as there is no `exports` for it.
- Why non-breaking spaces are used in README.md? Four such spaces are used in "Usage" section.

I would like to create a PR to fix the above if you can confirm it.

**Comment by achingbrain** [comment]
This appears to be fixed, please do open a PR if you spot anything else that is wrong.
