### ISSUE TITLE
Transitive dependency on `node-fetch`

### ISSUE THREAD

**Issue by locriacyber** [multiformats/js-multiaddr#241]
**Describe the bug**

When using Vite as bundler, it will fail when it cannot find `node-fetch`. However, if `node-fetch` is installed, the bundler will fail too, since Node API are not available in browser.

```
 WARN  Issues with peer dependencies found

.
└─┬ libp2p
  └─┬ libp2p-interfaces
    └─┬ multiaddr
      └─┬ dns-over-http-resolver
        └─┬ native-fetch
          └── ✕ missing peer node-fetch@"*"
```

**To Reproduce**
1. Download this project https://github.com/libp2p/js-libp2p/tree/master/examples/libp2p-in-the-browser
2. Run `pnpm install`
3. Run `pnpm start`

**Expected behavior**
`multiaddr` should not depend on `node-fetch`

**Comment by achingbrain** [comment]
`native-fetch` now has a peer dependency on `undici` rather than `node-fetch` so this issue may be resolved.  If you are still having problems please open an issue against `native-fetch` as that is where the fix would need to be applied.
