### ISSUE TITLE
Add /webrtc and /certhash

### ISSUE THREAD

**Issue by John-LittleBearLabs** [multiformats/js-multiaddr#261]
Analagous to the rust implementation:
https://github.com/multiformats/rust-multiaddr/pull/59/files#diff-d8c31d407e43532e4152070bdaf92d7fff58c81b39b4308cad7c769519d31376
And to the go implementation:
https://github.com/multiformats/go-multiaddr/pull/179/files

The goal is to be able to examine and use multiaddrs with these protocols in browserland, too. 
Will be useful to the js/ts implementation of the transport.

For reference:
https://github.com/libp2p/specs/pull/412

**Comment by ddimaria** [comment]
@John-LittleBearLabs Can I move this to Ready, In Progress, or In Review?  I think I saw you post on slack about a PR for this.

**Comment by John-LittleBearLabs** [comment]
> @John-LittleBearLabs Can I move this to Ready, In Progress, or In Review? I think I saw you post on slack about a PR for this.

@ddimaria 
I do not have a PR for it yet. In fact the code change I have locally at the moment does not work properly, and I can prove it. 

But perhaps "In Progress" isn't unreasonable.
