### ISSUE TITLE
[ERR_MODULE_NOT_FOUND]: Cannot find package 'dns' imported from  /Users/javaspeak/workspace3/symbiont/permanent_node/server/node_modules/@multiformats/multiaddr/dist/src/resolvers/dns.js

### ISSUE THREAD

**Issue by javaspeak** [multiformats/js-multiaddr#273]
Am running ipfs-js and get this error:

[ERR_MODULE_NOT_FOUND]: Cannot find package 'dns' imported from 
/Users/javaspeak/workspace3/symbiont/permanent_node/server/node_modules/@multiformats/multiaddr/dist/src/resolvers/dns.js

See:

https://github.com/ipfs/js-ipfs/issues/4161

Not sure what the issue is about.

Any guidance much appreciated.

Thank you

**Comment by achingbrain** [comment]
Please see the solution in https://github.com/ipfs/js-ipfs/issues/4161#issuecomment-1263680829
