### ISSUE TITLE
Drop is-ip dependency with alternative IP parsing fn

### ISSUE THREAD

**Issue by dapplion** [multiformats/js-multiaddr#282]
None of this implementations use regex

- Python standard library parse IPv6 function: https://github.com/python/cpython/blob/f8fb0d8e77a0ed765170595a48ff058711eb7fd8/Lib/ipaddress.py#L1607
- Go standard library parse IPv6 function: https://go.dev/src/net/ip.go

**Comment by mpetrunic** [comment]
Is this resolved with: https://github.com/multiformats/js-multiaddr/pull/280 ?

**Comment by dapplion** [comment]
Yes
