### ISSUE TITLE
Add /libp2p-websocket-star/ protocol

### ISSUE THREAD

**Issue by mkg20001** [multiformats/js-multiaddr#44]
See mkg20001/js-libp2p-websocket-star#1
The definition is the same as for libp2p-webrtc-star only the prefix needs to be changed

**Comment by lgierth** [comment]
Before we add new addresses resembling webrtc-star, let's revisit whether the encapsulation in webrtc is correct. cc @diasdavid

**Comment by diasdavid** [comment]
See: https://github.com/ipfs/js-ipfs/issues/981

**Comment by diasdavid** [comment]
There you go https://github.com/multiformats/js-multiaddr/pull/45 :)
