### ISSUE TITLE
What is a valid HTTP multiaddr?

### ISSUE THREAD

**Issue by alanshaw** [multiformats/js-multiaddr#53]
According to https://multiformats.io/multiaddr/ I should be able to type something like `/ip4/127.0.0.1/tcp/90/http/baz.jpg`

...but this causes `Error: no protocol with name: baz.jpg`

See https://runkit.com/embed/q1wgjxqmnn38

**Comment by alanshaw** [comment]
I'm guessing this is because I have an address + path...

**Comment by vmx** [comment]
The [README](https://github.com/multiformats/js-mafmt/blob/61955d24ef1bef3a66ddcbe002e395a1c0862fb5/README.md#mafmtformatmatchesmultiaddr) also mentions `/ip4/127.0.0.1/tcp/90/http/baz.jpg` so I expect it to be a valid address.

**Comment by vmx** [comment]
@diasdavid As you are the captain, can you please confirm?

**Comment by diasdavid** [comment]
@vmx the README was added on #14 and apparently I missed that `baz.jpg` was added, that shouldn't be there. Good catch!
