### ISSUE TITLE
Missing protocols in protocols-table.js

### ISSUE THREAD

**Issue by jtownson** [multiformats/js-multiaddr#63]
Hi there,

Please can you tell me why several of the protocols from protocols.csv are missing from the protocols-table.js.

I was sitting down to write a scala version multiaddr. The js version of multiaddr seems to be the canonical version from which I should copy. Just want to check I am not missing anything.

Thanks!

**Comment by jacobheun** [comment]
`protocols-table.js` now contains the most recent version of protocols.csv. The csv should contain the most up to date version of protocols as they are intended to be added there first.
