### ISSUE TITLE
Protocol p2p missing from list

### ISSUE THREAD

**Issue by jacogr** [multiformats/js-multiaddr#68]
Canonical CSV states "p2p preferred over ipfs" -

https://github.com/multiformats/multiaddr/blob/master/protocols.csv#L15

JS implementation is currently missing this new name/"alias" -

https://github.com/multiformats/js-multiaddr/blob/master/src/protocols-table.js#L39

Not a huge issue since specifying the `/ip4/127.0.0.1/tcp/30333/ipfs/QmWLtV5gpCzJCh9Eo7SxkrT3ZTApovHM1WpCY2Lp3XkaqF` does work, however a bit of an annoyance when one implementation (Rust) reports the protocol with `/p2p/` and there is some editing before it can be used in a JS client connecting to it.

However, it works, so not a massive issue apart from being a (small) annoyance.

**Comment by diasdavid** [comment]
Wanna submit a PR? :)

**Comment by jacogr** [comment]
Happy to do so. Only reason I haven't is that I have not dug deep enough to see if just adding an entry to the list with the correct id is enough - basically just duplicating as an alias. (Otherwise would have PR-ed instead of logging. It is getting towards the top of my annoyance list, so if somebody does't do it, will test locally, add and PR)
