### ISSUE TITLE
Quick validate if a string is a multi address

### ISSUE THREAD

**Issue by koalalorenzo** [multiformats/js-multiaddr#74]
I was not able to find in the docs and I am not sure if there is something for that: 
What I want to achieve is a clean way to test if an string is a multi address.

I am not sure if `is-ipfs` is helping, but I would like to validate specific multiaddr

Is there anything out there? If something pops up, I will comment a link here so other people can find it.

**Comment by mkg20001** [comment]
If you just want to check if it's a valid one use `try { multiaddr(string); return true; } catch(err) { return false }`

If you want to check if it matches a certain type of multiaddr take a look at [mafmt](npm.im/mafmt)

**Comment by koalalorenzo** [comment]
Is there a cleaner way, maybe using promises?

**Comment by koalalorenzo** [comment]
I think that `mafmt` solves my issue :) Thanks 👍

**Comment by mkg20001** [comment]
Note though that mafmt currently throws if the given multiaddress string is invalid. See https://github.com/multiformats/js-mafmt/pull/36 for a fix

**Comment by koalalorenzo** [comment]
Thank you! :)

I hope that PR will be merged soon
