### ISSUE TITLE
Cannot encode onion address

### ISSUE THREAD

**Issue by ricott1** [multiformats/js-multiaddr#88]
When I try to call `multiaddress()` on a onion address like `/onion/3g2upl4pq6kufc4m` I get an error in codec.bufferToTuples:
`Error: Error parsing address: Invalid address buffer: bc03`

Any idea how to solve this? Are onion addresses already implemented?

**Comment by jacobheun** [comment]
The code has been added to the protocol table but `convert.js` likely needs to be updated to handle the conversion. Adding some tests for various onion addresses and fixing the conversion code where needed would be the best path forward. Happy to review a PR if you'd be up for submitting one! :)

**Comment by ricott1** [comment]
Hi Jacob, thanks for the feedback. I changed the convert.js file to handle the onion and onion3 cases using the `str2buf(str)` function, but I really don't know if this is correct. I'm still getting an error: in `bufferToTuples` the size of the address that you get from 
`let size = sizeForAddr(p, buf.slice(i + n))`
is not correct. I suppose I'm doing something wrong, but I'm kinda lost now.

**Comment by jacobheun** [comment]
I'm not very familiar with onion addresses but looking at the go implementation there will need to be more in depth parsing of the string than just using `str2buf`. You can look at how go is doing the onion and onion3 transcoding, https://github.com/multiformats/go-multiaddr/blob/0460aad0fe51f7aa64d3a3c17854dc25368f7ca2/transcoders.go#L128-L213. The string needs to be split by `:` to determine the port.

It would also be good to leverage the same [bad](https://github.com/multiformats/go-multiaddr/blob/0460aad0fe51f7aa64d3a3c17854dc25368f7ca2/multiaddr_test.go#L35-L46) and [good](https://github.com/multiformats/go-multiaddr/blob/0460aad0fe51f7aa64d3a3c17854dc25368f7ca2/multiaddr_test.go#L97-L100) onion addresses from the go test suite when testing here.

**Comment by ricott1** [comment]
Ok, I wrote the following function into converter.js
`
const base32 = require('hi-base32')
function onion2buf(str) {
    const addr = str.split(':')
    if (addr.length !== 2) {
        throw new Error('failed to parse onion addr: ' + addr + ' does not contain a port number')
    }
    if (addr[0].length !== 16) {
        throw new Error('failed to parse onion addr: ' + addr[0] + ' not a Tor onion address.')
    }
    const buf = Buffer.from(base32.decode.asBytes(addr[0].toUpperCase()))
    const size = Buffer.from(varint.encode(buf.length))
    //onion port number
    
    const port = parseInt(addr[1], 10);
    
    if (port < 1 || port > 65536) {
        throw new Error("Port number is not in range(1, 65536)")
    }
    const portBuf = port2buf(port)
    return Buffer.concat([buf, portBuf])
}
`
I checked it against the python implementation and it gives the same result. I still have to understand your code 100%, but I think the general direction is correct. I'll finish up with the onion3 protocol and submit a pull in the next days.

**Comment by jacobheun** [comment]
Release in 6.1.0
