### ISSUE TITLE
Respect `.../ipfs/...` when it is passed?

### ISSUE THREAD

**Issue by achingbrain** [multiformats/js-multiaddr#99]
With `v7.x.x` the default name of protocol `421` was changed from `ipfs` to `p2p`.  This has led to the situation where this test will fail:

```javascript
it('parses a string and turns it back into a string', () => {
  const addr = '/ip4/73.109.217.58/tcp/49311/ipfs/QmWjxEGC7BthJrCf7QTModrcsRweHbupdPTY4oGMVoDZXm'
  const ma = multiaddr(addr)
  expect(ma.toString()).to.equal(addr)
})
```

It's weird because you could use `ipfs swarm connect .../ipfs/...` but then see `.../p2p/...` in the output of `ipfs swarm peers`.

**Comment by jacobheun** [comment]
> If the user passes in a .../ipfs/... multiaddr, should it be respected for that object instead of converting it to .../p2p/... or is this by design

It's by design. The goal is to completely migrate away from using 'ipfs' for the string representation. Eventually we should just see `p2p` everywhere. We could maintain that context locally, but I think it would unnecessarily convolute the code. Every address we get over the wire will use the default protocol name of 'p2p' as we only have the context of the code.

**Comment by achingbrain** [comment]
Yeah, I took that out of my comment because it's not even possible - if the multiaddr is converted to a buffer and back at any point that information is lost.

**Comment by jacobheun** [comment]
Right, and maintaining context of names that haven't been transmitted over buffers feels like an unnecessary waste, especially considering the sheer number of multiaddrs that are likely to be kept in memory. The conversion is weird, but it's temporary. Go is also converting, and Rust already uses p2p, so the prevalence in the wild of ipfs should disappear quickly as updates are rolled out.
